# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 63c4c931edb8c11aad9d6602f639875485220b0e8c5bbd2af3e451acc74c08740a67d86e50e8451d6a53281e3605b958c47c04e790acfb3a2cc7d19adb9d6c0a

test:
  secret_key_base: 3441aa7b304b8ed9a1c1704a34c35b0eb96653d7dc552c04d831629cbfaccf96747d941bfc9a4b7dfac3c7fba622e10ccb36872f39cd07173449fa06a48aaecc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
